name: Quick test

on:
  push:
    branches-ignore:
      - 'main'
      - '**skip**'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/quick.yml'
      - '.Rbuildignore'
      - 'data/**'
      - 'DESCRIPTION'
      - 'inst/tinytest/**'
      - 'man/**'
      - 'NAMESPACE'
      - 'R/**'
      - 'tests/**'
      - 'vignettes/**'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-18.04

    env:
      R_LIBS_USER: ~/rlibs
      R_COMPILE_AND_INSTALL_PACKAGES: never

    steps:
    - uses: actions/checkout@v2
    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-packages
    - name: Setup R
      run: |
        # R is already installed on GitHub's Ubuntu image
        Rscript --version
        # Create user library directory
        mkdir -p ${{ env.R_LIBS_USER }}
        echo 'R_LIBS_USER=${{ env.R_LIBS_USER }}' > $HOME/.Renviron
    - name: Install R packages
      run: Rscript scripts/install-dependencies.R
    - name: Session information
      run: sessionInfo()
      shell: Rscript {0}
    - name: Build and install
      run: |
        R CMD build --no-manual --no-build-vignettes .
        R CMD INSTALL --no-docs --no-multiarch --no-staged-install OmicNavigator_*.tar.gz
    - name: Test
      run: suppressMessages(tinytest::test_package("OmicNavigator"))
      shell: Rscript {0}
    - name: Run vignettes
      run: |
        vignettes <- Sys.glob("vignettes/*.Rnw")
        tangled <- sub("nw$", "", basename(vignettes))
        for (i in seq_along(vignettes)) {
          utils::Stangle(vignettes[i])
          source(tangled[i], local = new.env())
        }
      shell: Rscript {0}

  deploy-dev:
    needs: check
    if: ${{ github.ref == 'refs/heads/dev' && github.repository == 'abbvie-external/OmicNavigator' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy dev dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: abbvie-internal/OmicNavigatorCD
          event-type: deploy-dev
          # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
          client-payload: '{
            "repository": "${{ github.repository }}",
            "ref": "${{ github.ref }}",
            "sha": "${{ github.sha }}",
            "workflow": "${{ github.workflow }}",
            "run_id": "${{ github.run_id }}",
            "run_number": "${{ github.run_number }}"
          }'
